repos:
-   repo: local
    hooks:
    -   id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: rust
        types: [rust]
        pass_filenames: false
    -   id: cargo-test
        name: cargo test
        entry: cargo test
        language: rust
        types: [rust]
        pass_filenames: false
    -   id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt -- --check
        language: rust
        types: [rust]
