name: Shuttle Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prep .env
        run: |
          echo "LASTFM_KEY=${{ secrets.LASTFM_KEY }}" >> .env

      - name: Install Shuttle
      - uses: cargo-bins/cargo-binstall@main
        run: |
          cargo binstall -y --locked cargo-shuttle

      - name: Deploy
        run: shuttle deploy --id proj_01JGWTSA08EF54V8GT8HH5DDXE
        env:
          SHUTTLE_API_KEY: ${{ secrets.SHUTTLE_API_KEY }}
