name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  LASTFM_KEY: ${{secrets.LASTFM_KEY}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prep .env
      run: |
        echo "LASTFM_KEY=${{secrets.LASTFM_KEY}}" >> .env

    - name: Build Backend
      run: |
        cd backend
        cargo build --verbose

    - name: Build Frontend
      run: |
        cd frontend
        cargo install trunk wasm-bindgen-cli
        rustup target add wasm32-unknown-unknown
        trunk build --release

    - name: Run tests
      run: cargo test --verbose

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings -W clippy::pedantic

    - name: Check formatting
      run: cargo fmt -- --check
