name: Rust CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/checkout@v4

      - name: Prep .env
        run: |
          echo "LASTFM_KEY=${{ secrets.LASTFM_KEY }}" >> .env

      - name: Build Backend
        run: |
          cd backend
          cargo build --verbose

      - name: Build Frontend
        run: |
          cd frontend
          cargo install trunk wasm-bindgen-cli
          rustup target add wasm32-unknown-unknown
          trunk build --release

      - name: Run tests
        run: cargo test --verbose

      - name: Run Clippy
        run:
          cargo clippy --all-targets --all-features -- -D warnings -W
          clippy::pedantic

      - name: Check formatting
        run: cargo fmt -- --check
