name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env:
        LASTFM_USERNAME: ${{secrets.LASTFM_USERNAME}}
        LASTFM_KEY: ${{secrets.LASTFM_KEY}}
        GH_USERNAME: ${{secrets.GH_USERNAME}}
        GOODREADS_SHELF: ${{secrets.GOODREADS_SHELF}}
        LETTERBOXD_USERNAME: ${{secrets.LETTERBOXD_USERNAME}}
      run: cargo test --verbose
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings -W clippy::pedantic
    - name: Check formatting
      run: cargo fmt -- --check
